<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uniNDTotalMMALanguage" nsURI="http://www.moflon.org.uniNDTotalMMALanguage"
    nsPrefix="uniNDTotalMMALanguage">
  <eClassifiers xsi:type="ecore:EClass" name="RootA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" upperBound="-1" eType="#//A"
        containment="true" eOpposite="#//A/roota"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roota" lowerBound="1" eType="#//RootA"
        eOpposite="#//RootA/a"/>
  </eClassifiers>
</ecore:EPackage>
