<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BijectionMMBLanguage" nsURI="http://www.moflon.org.BijectionMMBLanguage"
    nsPrefix="BijectionMMBLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootb" lowerBound="1" eType="#//RootB"
        eOpposite="#//RootB/b"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootB">
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" upperBound="-1" eType="#//B"
        containment="true" eOpposite="#//B/rootb"/>
  </eClassifiers>
</ecore:EPackage>
